"""MCP Server Pack (Tier 3 bundle #13).

Manage and generate Model Context Protocol servers so the agent can
expose its capabilities to external LLM hosts (or consume third-party
MCP tools). Includes a ready security-scanner MCP server generator.
"""
import importlib.util
import json
import os
import subprocess
import sys
import time

MCP_DIR = os.path.join(os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))), "mcp_servers")

SERVER_TEMPLATE = '''"""MCP server: {name} (generated by mcp_toolkit).
Run with: python mcp_servers/{fname}
"""
import json

# minimal MCP-ish JSON-RPC dispatch (no external deps required)
TOOLS = {tools!r}


def main():
    import sys
    sys.path.insert(0, ".")
    print(json.dumps({{"server": "{name}", "tools": list(TOOLS.keys()),
                       "status": "ready"}}))
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
        except Exception:
            continue
        method = req.get("method") or req.get("tool") or ""
        params = req.get("params") or {{}}
        if method == "ping":
            print(json.dumps({{"jsonrpc": "2.0", "result": "pong"}}))
        elif method in TOOLS:
            try:
                result = TOOLS[method](**params)
                print(json.dumps({{"jsonrpc": "2.0", "result": result}}))
            except Exception as exc:
                print(json.dumps({{"jsonrpc": "2.0", "error": str(exc)}}))
        else:
            print(json.dumps({{"jsonrpc": "2.0", "error": "unknown tool: " + str(method)}}))


if __name__ == "__main__":
    main()
'''


def _err(msg):
    return json.dumps({"error": msg}, ensure_ascii=False)


def tool_mcp_list():
    """List all available MCP servers in the mcp_servers directory."""
    try:
        os.makedirs(MCP_DIR, exist_ok=True)
        servers = []
        for fn in sorted(os.listdir(MCP_DIR)):
            if fn.endswith(".py") and not fn.startswith("_"):
                path = os.path.join(MCP_DIR, fn)
                st = os.stat(path)
                servers.append({"file": fn, "size": st.st_size,
                                "mtime": time.strftime("%Y-%m-%d %H:%M", time.localtime(st.st_mtime))})
        return json.dumps({"ok": True, "mcp_dir": MCP_DIR,
                           "count": len(servers), "servers": servers},
                          ensure_ascii=False, indent=2)
    except Exception as exc:
        return _err("mcp_list failed: %r" % exc)


def tool_mcp_server_build(name="scanner", tools="port_scan,subdomains",
                          output_path=""):
    """Generate a new standalone MCP server file (JSON-RPC line protocol)
    with the given tool list. Stubs are returned as functional
    placeholders the operator can extend."""
    try:
        if not name:
            return _err("server name required")
        tlist = [t.strip() for t in (tools or "port_scan,subdomains").split(",") if t.strip()]

        # build a small stub function table
        stub_funcs = {}
        for t in tlist:
            stub_funcs[t] = (lambda tname=t: (lambda **kw: {
                "note": "stub - implement %s in mcp_servers/%s.py" % (tname, name),
                "args": kw}))()

        fname = "mcp_%s.py" % name
        path = output_path or os.path.join(MCP_DIR, fname)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        code = SERVER_TEMPLATE.format(name=name, fname=fname, tools=stub_funcs)
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)
        return json.dumps({
            "ok": True, "server": name, "path": path,
            "tools": tlist,
            "run": "python %s" % path,
            "next": "edit %s to implement each tool body (see ai_agent/tools for ready impls)"
                    % path,
        }, ensure_ascii=False, indent=2)
    except Exception as exc:
        return _err("mcp_build failed: %r" % exc)


def tool_mcp_scanner_server(output_path=""):
    """Generate the security-scanner MCP server preloaded with real
    tool bodies: dns_recon, port_scan, http_probe - lightweight
    dependency-free implementations using only the stdlib."""
    try:
        path = output_path or os.path.join(MCP_DIR, "mcp_scanner.py")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        code = '''"""Security scanner MCP server - stdlib only (no deps)."""
import json, socket, sys
from urllib.parse import urlparse


def dns_recon(host="", qtype="A"):
    import socket as s
    try:
        return {"host": host, "resolved": s.gethostbyname_ex(host)[2][:20]}
    except Exception as exc:
        return {"host": host, "error": str(exc)}


def port_scan(host="127.0.0.1", ports="21,22,80,443,3306,3389,8080"):
    open_ports = []
    for p in [int(x) for x in ports.split(",") if x.strip()]:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.5)
            try:
                if s.connect_ex((host, p)) == 0:
                    open_ports.append(p)
            except Exception:
                pass
    return {"host": host, "open_ports": open_ports}


def http_probe(url="http://127.0.0.1/"):
    import urllib.request
    try:
        with urllib.request.urlopen(url, timeout=8) as r:
            return {"url": url, "status": r.status,
                    "server": r.headers.get("Server", ""),
                    "len": len(r.read(4096))}
    except Exception as exc:
        return {"url": url, "error": str(exc)}


TOOLS = {"dns_recon": dns_recon, "port_scan": port_scan,
         "http_probe": http_probe}
    
if __name__ == "__main__":
    print(json.dumps({"server": "mcp_scanner",
                      "tools": list(TOOLS.keys()), "status": "ready"}))
'''
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)
        return json.dumps({"ok": True, "server": "mcp_scanner", "path": path,
                           "tools": ["dns_recon", "port_scan", "http_probe"],
                           "run": "python %s" % path},
                          ensure_ascii=False, indent=2)
    except Exception as exc:
        return _err("mcp_scanner failed: %r" % exc)


def tool_mcp_test(server_path="", action="selftest"):
    """Test an MCP server file: import check, syntax check or a live
    ping round-trip (action=selftest|ping|syntax)."""
    try:
        path = server_path or os.path.join(MCP_DIR, "local_fs_demo.py")
        if not os.path.exists(path):
            return json.dumps({"error": "server file not found: %s" % path},
                              ensure_ascii=False)
        if action == "syntax":
            rc = subprocess.run([sys.executable, "-m", "py_compile", path],
                                capture_output=True, text=True, timeout=30)
            return json.dumps({"ok": rc.returncode == 0, "path": path,
                               "stderr": rc.stderr[-400:]}, ensure_ascii=False, indent=2)
        if action == "ping":
            rc = subprocess.run([sys.executable, path],
                                input="{\"method\":\"ping\"}\\n", capture_output=True,
                                text=True, timeout=30)
            return json.dumps({"ok": rc.returncode == 0, "path": path,
                               "output": (rc.stdout or rc.stderr)[-400:]},
                              ensure_ascii=False, indent=2)
        # selftest = import + syntax
        rc = subprocess.run([sys.executable, "-m", "py_compile", path],
                            capture_output=True, text=True, timeout=30)
        return json.dumps({"ok": rc.returncode == 0, "path": path,
                           "mode": "selftest", "syntax": "valid" if rc.returncode == 0 else "INVALID",
                           "stderr": rc.stderr[-400:]}, ensure_ascii=False, indent=2)
    except Exception as exc:
        return _err("mcp_test failed: %r" % exc)